meta_product_name: "Helper"
meta_title: "Helper - Professional help for your home"
meta_description: "Easily find help for any home renovation project. Helper connects you with the best in the construction near you"
meta_image: "cover.png" # should exist in `app/assets/images/`
