meta_product_name: "Helper"
meta_title: "Helper - Professional solutions for your home"
meta_description: "Easily find help for any home renovation project. Helper connects you with the best in the construction industry near you"
meta_image: "renovation.png" # should exist in `app/assets/images/`
meta_url: "www.helper.solutions"
